spring:
  application:
    name: distributor

  datasource:
    username: develop
    password: develop
    url: jdbc:postgresql://localhost:5432/distributor-db
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC

server:
  port: 4041

logging:
  level:
    com.distributor: DEBUG

application:
  jwt:
    secret: "Illseeyouonthedarksideofthemoon"
    expiration: 86400000
  internal:
    secret: "Illseeyouonthedarksideofthemoon"
  host:
    url: http://localhost:4041
